version: '3'
services:
  api:
    container_name: dream-big-api
    build: ./dream-big-api
    ports:
      - "3000:3000"
    volumes:
      - ./dream-big-api:/api
    depends_on:
      - dev-db
    environment:
      RAILS_ENV: 'development'
      DEV_DB_DATABASE: 'dream_big_api_development'
      DEV_DB_USERNAME: dream
      DEV_DB_PASSWORD: pwd
      DEV_DB_HOST: dream-big-dev-db
    command:
      /bin/bash -c 'rm -f /api/tmp/pids/server.pid && bundle install && rails s -b 0.0.0.0'
  # ui:
  #   container_name: dream-big-ui
  #   build: ./dream-big-ui
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./dream-big-ui:/dream-big-ui
  #   depends_on:
  #     - api
  #   command:
  #     /bin/bash -c 'npm install; npm start'
  dev-db:
    container_name: dream-big-dev-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: dream_big_api_development
      MYSQL_USER: dream
      MYSQL_PASSWORD: pwd

    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/mysql